### ISSUE TITLE
Swig versions 3.0.9 and 3.0.10 are incompatible with lldb.

### ISSUE THREAD

**Issue by emarashliev** [uraimo/buildSwiftOnARM#19]
On RASPBIAN STRETCH LITE 4.14 (Linux raspberrypi 4.14.50-v7+)
The compilation fails with `Swig versions 3.0.9 and 3.0.10 are incompatible with lldb.`
https://github.com/llvm-mirror/lldb/blob/4649417b4a7d1e23080ca1c62a31db0739eee7df/scripts/lldb.swig#L52
It happens because the version go Swig is 3.0.10.

**Comment by uraimo** [comment]
Hi Emil!
You can install manually 3.0.12:
```
wget http://ftp.de.debian.org/debian/pool/main/s/swig/swig_3.0.12-1.1_armhf.deb
wget http://ftp.de.debian.org/debian/pool/main/s/swig/swig3.0_3.0.12-1.1_armhf.deb

sudo dpkg -i swig3.0_3.0.12-1.1_armhf.deb swig_3.0.12-1.1_armhf.deb
```

See [post](https://www.uraimo.com/2018/06/13/A-big-update-on-Swift-4-1-2-for-raspberry-pi-zero-1-2-3/).
