### ISSUE TITLE
bad instruction on README

### ISSUE THREAD

**Issue by abesmon** [uraimo/buildSwiftOnARM#22]
readme says to install swig with commands:
```
wget http://ftp.de.debian.org/debian/pool/main/s/swig/swig_3.0.12-1.1_armhf.deb
wget http://ftp.de.debian.org/debian/pool/main/s/swig/swig3.0_3.0.12-1.1_armhf.deb
sudo dpkg -i swig3.0_3.0.12-1.1_armhf.deb swig_3.0.12-1.1_armhf.deb
```

but it seems, that there is no `swig_3.0.12-1.1`, only `swig_3.0.12-1.2`, also no `swig3.0_3.0.12-1.1`, but there is `swig3.0_3.0.12-1.2`

**Comment by uraimo** [comment]
Thanks, I've updated the readme.
