### ISSUE TITLE
3.1+ build fails on the latest Raspbian

### ISSUE THREAD

**Issue by uraimo** [uraimo/buildSwiftOnARM#4]
Just to document this failure (when compiling swift/ ), Bouke kindly opened an issue on jira: https://bugs.swift.org/browse/SR-4613

**Comment by nesty** [comment]
On the latest Raspbian version (Stretch) released last week, Swift 3.1.1 (without swiftpm) compiles without issues (probably thanks to clang-3.8).

**Comment by uraimo** [comment]
Great news @nesty, thank you for the update!
I'm going to close this, since it's not a problem anymore.

If someone wants to update their installation, the release post contains instructions, [here](https://www.raspberrypi.org/blog/raspbian-stretch/).

**Comment by uraimo** [comment]
@nesty did you compile libdispatch too? And if it worked, did you build it on a fresh Raspbian Stretch image?

It looks like that Raspbian has an obsolete linux-libc-dev 3.18.5-1~exp1+rpi19+stretch that lacks the essential membarrier.h (present in newer releases).

**Comment by carlhung** [comment]
i want swift package manager badly.

**Comment by uraimo** [comment]
@carlhung here, Swift 3.1.1 with SPM: https://www.dropbox.com/s/v6oslfta6u773rj/swift-3.1.1-RPi23-RaspbianStretchAug17.tgz?dl=0

You'll need to do a dist-upgrade of your old Raspbian to use it (see instructions at the bottom of [this post](https://www.raspberrypi.org/blog/raspbian-stretch/)).

**Comment by carlhung** [comment]
Thanks! Amazing!

**Comment by nesty** [comment]
@uraimo yes I also did compile libdispatch successfully after adding the missing membarrier.h file and editing unistd.h to add the missing membarrier syscall.

Thank you for the update to compile swiftpm successfully on Raspbian Stretch 👍.

**Comment by carlhung** [comment]
Will you release for pi zero? As i just got a pi zero.

**Comment by uraimo** [comment]
Since it takes nearly 2 weeks, I think I'll wait for High Sierra release (19th sept?) to build directly 3.2 when they create a tag on the swift-3.1-branch.
