### ISSUE TITLE
[armv6][5.0] Prebuilt binary runs, fails to compile with unknown error

### ISSUE THREAD

**Issue by idrougge** [uraimo/buildSwiftOnARM#48]
I downloaded and extracted the ARMv6 5.0 binary according to instructions to my RPi 1b with Raspbian, installing the additional required packages with `sudo apt install clang-3.8 libicu-dev libcurl4-nss-dev` and added the extracted `usr` directory to the path.

Running `swift test.swift` will run the source file in question, but compiling to a file with `swiftc test.swift` always fails with `<unknown>:0: error: unable to execute command: <unknown>` at the end of compilation.

System info:
```
Linux raspberrypi 4.14.71+ #1145 Fri Sep 21 15:06:38 BST 2018 armv6l

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
```

**Comment by uraimo** [comment]
This should 99% fix it, I suppose you didn't register clang-3.8 with the alternatives for `clang`:

```
sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.8 100
sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.8 100
```

**Comment by idrougge** [comment]
This works perfectly. Should this be added to the readme?

**Comment by uraimo** [comment]
I thought it was already there but it wasn't... Just added :)
