### ISSUE TITLE
[Ubuntu1804][5.1][GitHub CI] SPM: error: toolchain is invalid: could not find the `swiftc` at expected path

### ISSUE THREAD

**Issue by uraimo** [uraimo/buildSwiftOnARM#56]
Noticed this on a container with armv7 Ubuntu 18.04, when running `swift test` and likely other spm commands:

```
error: toolchain is invalid: could not find the `swiftc` at expected path /github/workspace/usr/bin/swiftc
```

No issues on Debian Buster.
Needs investigation, could be just a fluke.

**Comment by uraimo** [comment]
Like #57 I haven't verified by I suspect it depends on the fact that it was running in a docker container on Github CI.

**Comment by uraimo** [comment]
Working fine on a Docker container with `overlay2` storage driver.

**Comment by uraimo** [comment]
Closing this since it's an issue specific to GitHub CI or their docker config (still in beta).

**Comment by maximkrouk** [comment]
Have the same issue on VPS without docker, `swift build` causes this error

**Comment by uraimo** [comment]
@maximkrouk Hi! can you paste the `uname -a` for that VPS and tell me which vps provider are you using?
Thanks!

**Comment by maximkrouk** [comment]
The provider is [Hostinger](hostinger.com), VPS is running Ubuntu Linux 18.04, I was tried to run `swift build -c release --disable-sandbox` on Vapor[vapor.codes] toolbox.
`Linux <hostname> 4.15.0 #1 SMP Thu Jun 27 15:10:55 MSK 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by maximkrouk** [comment]
No errors after changing my VPS system to Ubuntu16.04 c:

**Comment by xnutsive** [comment]
I've just hit this with Ubuntu 18.04 in Docker on a mac. I'll try the storage driver you suggested, @uraimo, and report back.
